name: flutter_github_viewer
description: A Flutter application to view GitHub repositories.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  auto_route: ^7.4.0
  dartz: ^0.10.1
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.6
  http: ^1.0.0
  oauth2: ^2.0.2
  webview_flutter: ^4.2.2

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5

flutter:
  uses-material-design: true
