@baseURL = https://api.github.com
@token = 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
@acceptHeader = application/vnd.github.v3.html+json

GET {{baseURL}}/user/starred?page=1
Authorization: token {{token}}
Accept: {{acceptHeader}}

###

GET {{baseURL}}/search/repositories?q=portfolio&page=1
Authorization: token {{token}}
Accept: {{acceptHeader}}

###
GET {{baseURL}}/repos/flutter/flutter/readme
Authorization: token {{token}}
Accept: {{acceptHeader}}

###
PUT {{baseURL}}/user/starred/flutter/flutter
Authorization: token {{token}}
Accept: {{acceptHeader}}
Content-Length: 0

###
DELETE {{baseURL}}/user/starred/flutter/flutter
Authorization: token {{token}}
Accept: {{acceptHeader}}

###
GET {{baseURL}}/user/starred/flutter/flutter
Authorization: token {{token}}
Accept: {{acceptHeader}}
