@baseURL = https://api.github.com
@token = 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
@acceptHeader = application/vnd.github.v3.html+json

GET {{baseURL}}/user/starred?page=1
Authorization: token {{token}}
Accept: {{acceptHeader}}
If-None-Match: W/"4e05e3a0b0d495ce9c9411f8900d00d9b03953a5557aba06e668783dd0c12b3f"

###

GET {{baseURL}}/search/repositories?q=portfolio&page=1
Authorization: token {{token}}
Accept: {{acceptHeader}}

###
GET {{baseURL}}/repos/flutter/flutter/readme
Authorization: token {{token}}
Accept: {{acceptHeader}}

###
PUT {{baseURL}}/user/starred/flutter/flutter
Authorization: token {{token}}
Accept: {{acceptHeader}}
Content-Length: 0

###
DELETE {{baseURL}}/user/starred/flutter/flutter
Authorization: token {{token}}
Accept: {{acceptHeader}}

###
GET {{baseURL}}/user/starred/flutter/flutter
Authorization: token {{token}}
Accept: {{acceptHeader}}
